#!/usr/bin/env bash
#
# Merge unk deduped.temp from unaligned.fastqs  before deduplication (again)
#
#PBS -W group_list=bhurwitz
#PBS -j oe
#PBS -o ./out/
#PBS -q qualified
#PBS -l select=1:ncpus=1:mem=216gb
###and the amount of time required to run it
#PBS -l walltime=6:00:00
#PBS -l cput=6:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

cd $PBS_O_WORKDIR

set -u
source ./config.sh

if [[ ! -d $GROUPED_DIR ]]; then
    mkdir -p $GROUPED_DIR
fi

cd "$UNK_DIR"

echo Concatenating all those deduped temp files

if [[ ! -e $GROUPED_DIR/all-deduped.temp ]]; then
    time find ./ -type f -iname "deduped.temp" -print0 | xargs -0 -I file cat file > $GROUPED_DIR/all-deduped.temp
fi

echo Deduplicating once again

time fastq filter --unique $GROUPED_DIR/all-deduped.temp \
    > $GROUPED_DIR/$UNKSPEC

if [[ $? = 0 ]]; then #no error in fastq filter
    if [[ ! -z $GROUPED_DIR/$UNKSPEC ]]; then #and output is not zero-length
        echo Looks like things worked
        echo Removing temp file 
        rm $GROUPED_DIR/all-deduped.temp
    fi
fi

echo DONE at $(date)

