#!/usr/bin/env bash
#
# Get paired and single reads from the deduped fastq's
#
#PBS -W group_list=bhurwitz
#PBS -j oe
#PBS -o ./out/
#PBS -q qualified
#PBS -l select=1:ncpus=12:mem=72gb
###and the amount of time required to run it
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

cd $PBS_O_WORKDIR

set -u
source ./config.sh

if [[ ! -d $READY_DIR ]]; then
    mkdir -p $READY_DIR
fi

cd "$DEDUPED_DIR"

extract-paired-reads.py -d $READY_DIR --gzip $DEDUPED_DIR/all-deduped.fastq

echo Done at $(date)

