#!/usr/bin/env bash
#
# Get paired and single reads from the deduped fastq's
#
#PBS -W group_list=bhurwitz
#PBS -j oe
#PBS -N 04-get-paired
#PBS -o ./out/
#PBS -q qualified
#PBS -l select=1:ncpus=12:mem=72gb
###and the amount of time required to run it
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

cd $PBS_O_WORKDIR

set -u
source ./config.sh

if [[ ! -d $READY_DIR ]]; then
    mkdir -p $READY_DIR
fi

cd "$SORTED_DIR"

#going to try the perl script this time and see if its faster
#this takes 7.5 hours
#extract-paired-reads.py -f -d $READY_DIR --gzip $SORTED_DIR/sorted-all-deduped.fastq

echo Have to split up the interleaved reads again ja ja ja
time cat sorted-all-deduped.fastq | paste - - - - | egrep '@.*\/1.*' | tr '\t' '\n' > sorted-all-deduped.1
time cat sorted-all-deduped.fastq | paste - - - - | egrep '@.*\/2.*' | tr '\t' '\n' > sorted-all-deduped.2

echo Ok now run the perl script to merge and shuffle cha cha cha
time $WORKER_DIR/mergeShuffledFastqSeqs.pl \
    -f1 sorted-all-deduped.1 \
    -f2 sorted-all-deduped.2 \
    -r '^@(\S+)/[1|2]$' \
    -o $READY_DIR/assemble-me

echo Done at $(date)

