#!/usr/bin/env bash
#
# Sort fastq for extract-paired-reads.py
#
#PBS -W group_list=bhurwitz
#PBS -j oe
#PBS -N 04-opt-sort-fastq
#PBS -o ./out/
#PBS -q qualified
#PBS -l select=1:ncpus=12:mem=72gb
###and the amount of time required to run it
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

cd $PBS_O_WORKDIR

set -u
source ./config.sh

if [[ ! -d $SORTED_DIR ]]; then
    mkdir -p $SORTED_DIR
fi

cd "$DEDUPED_DIR"

cat $DEDUPED_DIR/all-deduped.fastq | paste - - - - | sort -k1,1 -S 70G | tr '\t' '\n' > $SORTED_DIR/sorted-all-deduped.fastq

echo Done at $(date)

