#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -q qualified
#PBS -j oe
#PBS -N 05-megahit
#PBS -o ./out/
#PBS -l select=1:ncpus=12:mem=72gb
###and the amount of time required to run it
#PBS -l walltime=24:00:00
#PBS -l cput=96:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

if [ -n "$PBS_O_WORKDIR" ]; then
    cd $PBS_O_WORKDIR
fi

set -u

source ./config.sh

COMMON="$WORKER_DIR/common.sh"

if [ -e $COMMON ]; then
  . "$COMMON"
else
  echo Missing common \"$COMMON\"
  exit 1
fi

cd $READY_DIR

time megahit \
    --num-cpu-threads 12 \
    --memory 0.9 \
    --presets meta-large \
    --out-prefix unknown \
    --12 sorted-all-deduped.fastq.pe \
    -r sorted-all-deduped.fastq.se \
    -o "$CONTIG_DIR"

echo "Ended at $(date)"
